<nav>
    <a href="contact.php">Contact</a>
    <a href="webographie.php" class="NavSelected">Les Ressources</a>
    <a href="lieux.php">Les Batailles</a>
    <a href="camps.php">Les Camps</a>
    <a href="tombes.php">Les Tombes</a>
    <a href="hopitaux/hopitaux.php">Les Hôpitaux</a>
    <a href="poilus.php">Les Poilus</a>
</nav>

<div id="navbis">
    <a href="bibliographie.php">Les ressources bibliographiques</a>&nbsp;&nbsp;|&nbsp;&nbsp;
    <a href="webographie.php">Les ressources en ligne</a>
</div>