    <div class="col-4 text-center my-3 align-self-center">

        <a href="index.php" title="retour sur la page d'accueil du site">
        <img src="images/logo.png" class="logo" alt="Logo du site Histoires de Poilus" style="width:80%"/></a>
        
    </div>
  
    <div class="col-4 text-center my-3 border-left border-right">

        <h5>Les petits plus</h5>

        <a href="/mentions.php">Mentions Légales</a><br />
        <a href="/contact.php">Pour me contacter</a><br />
        <a href="http://www.genealexis.fr">Généalexis</a><br />
        <a href="/index_noms.php">Soldats mentionnés</a><br />
        <a href="/plan_du_site.php">Plan du site</a><br />
        <a href="/cookies.php">Cookies</a>
        
    </div>

    <div class="col-4 text-center my-3 align-self-center">

        <h5>Suivez-moi !</h5>
 
        <div style="font-size: 2.6em;">
            <a href="https://www.facebook.com/sharer.php?u=<?php echo $url; ?>" title="Partager cette page sur Facebook">
            <i class="fab fa-facebook"></i></a>
            <a href="https://www.instagram.com/alexisamand/" title="Voir le compte Instagram du webmaster">
            <i class="fab fa-instagram"></i></a>
            <a href="https://twitter.com/intent/tweet?url=<?php echo $url; ?>" title="Partager cette page sur Twitter">
            <i class="fab fa-twitter-square"></i></a>
            <a href="https://www.linkedin.com/shareArticle?mini=true&url=<?php echo $url; ?>" title="Partager cette page sur LinkedIn"> 	
            <i class="fab fa-linkedin"></i></a>
        </div>

    </div>

    <div class="col-12 text-center">

    <br /><br />Copyright &copy; 2014-<?php echo date('Y'); ?> - Alexis AMAND<br />Tous droits réservés

    </div>