    <div class="col-md-4 text-center my-3 align-self-center col-12 order-md-1 order-3">

        <a href="/index.php" title="retour sur la page d'accueil du site">
        <img src="/images/grand-logo.svg" alt="Logo du site Histoires de Poilus" style="width:100%;"/></a>

    </div>

    <div class="col-md-4 text-center my-3 border-left border-right col-6 order-md-2 order-2 masque-border">

        <h5>Les petits plus</h5>

        <a href="/mentions.php" title="Mentions légales du site Histoires de Poilus">Mentions Légales</a><br />
        <a href="#contactModal" data-toggle="modal" data-target="#contactModal">Pour me contacter</a><br />
        <a href="http://www.genealexis.fr" title="Genealexis : Histoires d'hier et d'aujourd'hui" target="_blank">Genealexis.fr</a><br />
        <a href="/index_noms.php" title="Liste des soldats mentionnés sur le site">Soldats mentionnés</a><br />
        <a href="/plan-du-site.php" title="plan du site">Plan du site</a><br />
        <a href="/cookies.php" title="information sur l'utilisation des cookies">Cookies</a>

    </div>

    <div class="col-md-4 text-center my-3 align-self-center col-6 order-md-3 order-1">

        <h5>Suivez-moi !</h5>

        <div style="font-size: 2.6em;">
            <a href="https://www.facebook.com/genealexis.fr>" title="Page Facebook de Généalexis" target="_blank">
            <i class="fab fa-facebook"></i></a>
            <a href="https://www.instagram.com/alexisamand/" title="Compte Instagram d'Alexis AMAND" target="_blank">
            <i class="fab fa-instagram"></i></a>
            <a href="https://twitter.com/alexisamand" title="Compte Twitter d'Alexis AMAND" target="_blank">
            <i class="fab fa-twitter-square"></i></a>
            <a href="https://www.linkedin.com/in/alexis-amand-99775817/" title="Profil d'Alexis AMAND sur Linkedin" target="_blank">
            <i class="fab fa-linkedin"></i></a>
        </div>

    </div>

    <div class="col-12 text-center order-4">

        <br /><br />Copyright &copy; 2014-<?php echo date('Y'); ?> - Tous droits réservés<br />
        Site réalisé par <a href="https://www.boitasite.com" title="Création et référencement de sites" target="_blank">Boitasite</a>

    </div>