	<a href="/mentions.php">Mentions Légales</a>&nbsp;&nbsp;|&nbsp;&nbsp;
    <a href="/contact.php">Contact</a>&nbsp;&nbsp;|&nbsp;&nbsp;
    <a href="http://www.genealexis.fr">Généalexis</a>&nbsp;&nbsp;|&nbsp;&nbsp;
    <a href="/cookies.php">Cookies</a>&nbsp;&nbsp;|&nbsp;&nbsp;
    <a href="/erreur.php#plan">Plan du site</a>
    <br><br>Copyright &copy; 2014-<?php echo date('Y'); ?> - Alexis AMAND<br>Tous droits réservés
