    <div class="col-md-4 text-center my-3 align-self-center col-12 order-md-1 order-3">

        <a href="index.php" title="retour sur la page d'accueil du site">
        <img src="/images/petit-logo.jpg" alt="Logo du site Histoires de Poilus"/></a>

    </div>

    <div class="col-md-4 text-center my-3 border-left border-right col-6 order-md-2 order-2 masque-border">

        <h5>Les petits plus</h5>

        <a href="#">Mentions Légales</a><br />
        <a href="#exampleModal" data-toggle="modal" data-target="#exampleModal">Pour me contacter</a><br />
        <a href="#">Genealexis.fr</a><br />
        <a href="#">Soldats mentionnés</a><br />
        <a href="#">Plan du site</a><br />
        <a href="#">Cookies</a>

    </div>

    <div class="col-md-4 text-center my-3 align-self-center col-6 order-md-3 order-1">

        <h5>Suivez-moi !</h5>

        <div style="font-size: 2.6em;">
            <a href="#>" title=" ">
            <i class="fab fa-facebook"></i></a>
            <a href="#" title=" ">
            <i class="fab fa-instagram"></i></a>
            <a href="#" title=" ">
            <i class="fab fa-twitter-square"></i></a>
            <a href="#" title=" ">
            <i class="fab fa-linkedin"></i></a>
        </div>

    </div>

    <div class="col-12 text-center order-4">

        <br /><br />Copyright &copy; 2014-<?php echo date('Y'); ?> - Tous droits réservés<br />
        Site réalisé par <a href="https://www.boitasite.com">Boitasite</a>

    </div>
