<div class="container">

    <div class="row">

        <div class="col-12 text-center">

            <a href="/">
            
                <img src="/images/grand-logo.svg" class="logo" alt="Logo du site Histoires de Poilus"/></a>

            </a>

        </div>

        <div class="col-12">

            <nav class="navbar navbar-expand-lg navbar-light">
            
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav mx-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Les Poilus
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="/poilus.php" title="Qu'est-ce qu'un poilu ?">A propos des poilus</a>
                        <a class="dropdown-item" href="/index_noms.php" title="Liste des noms de soldats cités sur le site">Index des noms cités</a>
                        <a class="dropdown-item" href="/poilus/lacourt-onesime.php" title="Biographies de soldats originaires des Ardennes">Les poilus des Ardennes</a>
                        <a class="dropdown-item" href="/poilus/FROIDUROT-Alfred.php" title="Biographies de soldats originaires de la Côte-d'Or">Les poilus de la Côte-d'Or</a>
                        <a class="dropdown-item" href="/poilus/arnould-gaston.php" title="Biographies de soldats originaires de la Marne">Les poilus de la Marne</a>
                        <a class="dropdown-item" href="/poilus/amand-hoche.php" title="Biographies de soldats originaires du Nord">Les poilus du Nord</a>
                        <a class="dropdown-item" href="/poilus/amand-jules.php" title="Biographies de soldats originaires de Belgique">Les jasses de Belgique</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Les Hôpitaux
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="/poilus.php" title="Qu'est-ce qu'un poilu ?">A propos des poilus</a>
                        <a class="dropdown-item" href="/index_noms.php" title="Liste des noms de soldats cités sur le site">Index des noms cités</a>
                        <a class="dropdown-item" href="/poilus/lacourt-onesime.php" title="Biographies de soldats originaires des Ardennes">Les poilus des Ardennes</a>
                        <a class="dropdown-item" href="/poilus/FROIDUROT-Alfred.php" title="Biographies de soldats originaires de la Côte-d'Or">Les poilus de la Côte-d'Or</a>
                        <a class="dropdown-item" href="/poilus/arnould-gaston.php" title="Biographies de soldats originaires de la Marne">Les poilus de la Marne</a>
                        <a class="dropdown-item" href="/poilus/amand-hoche.php" title="Biographies de soldats originaires du Nord">Les poilus du Nord</a>
                        <a class="dropdown-item" href="/poilus/amand-jules.php" title="Biographies de soldats originaires de Belgique">Les jasses de Belgique</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                    Les Tombes
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Les Camps
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="/poilus.php" title="Qu'est-ce qu'un poilu ?">A propos des poilus</a>
                        <a class="dropdown-item" href="/index_noms.php" title="Liste des noms de soldats cités sur le site">Index des noms cités</a>
                        <a class="dropdown-item" href="/poilus/lacourt-onesime.php" title="Biographies de soldats originaires des Ardennes">Les poilus des Ardennes</a>
                        <a class="dropdown-item" href="/poilus/FROIDUROT-Alfred.php" title="Biographies de soldats originaires de la Côte-d'Or">Les poilus de la Côte-d'Or</a>
                        <a class="dropdown-item" href="/poilus/arnould-gaston.php" title="Biographies de soldats originaires de la Marne">Les poilus de la Marne</a>
                        <a class="dropdown-item" href="/poilus/amand-hoche.php" title="Biographies de soldats originaires du Nord">Les poilus du Nord</a>
                        <a class="dropdown-item" href="/poilus/amand-jules.php" title="Biographies de soldats originaires de Belgique">Les jasses de Belgique</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Les Batailles
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="/poilus.php" title="Qu'est-ce qu'un poilu ?">A propos des poilus</a>
                        <a class="dropdown-item" href="/index_noms.php" title="Liste des noms de soldats cités sur le site">Index des noms cités</a>
                        <a class="dropdown-item" href="/poilus/lacourt-onesime.php" title="Biographies de soldats originaires des Ardennes">Les poilus des Ardennes</a>
                        <a class="dropdown-item" href="/poilus/FROIDUROT-Alfred.php" title="Biographies de soldats originaires de la Côte-d'Or">Les poilus de la Côte-d'Or</a>
                        <a class="dropdown-item" href="/poilus/arnould-gaston.php" title="Biographies de soldats originaires de la Marne">Les poilus de la Marne</a>
                        <a class="dropdown-item" href="/poilus/amand-hoche.php" title="Biographies de soldats originaires du Nord">Les poilus du Nord</a>
                        <a class="dropdown-item" href="/poilus/amand-jules.php" title="Biographies de soldats originaires de Belgique">Les jasses de Belgique</a>
                    </div>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Les Ressources
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="/guides/parcours-soldat.php" title="Comment retrouver le parcours d'un poilu">Comment retrouver un poilus ?</a>
                        <a class="dropdown-item" href="/ressources/historiques-regiments.php" title=" ">Les historiques de régiments</a>
                        <a class="dropdown-item" href="/bibliographie.php" title=" ">Les ressources bibliographiques</a>
                        <a class="dropdown-item" href="/webographie.php" title=" ">Les ressources en ligne</a>
                    </div>
                </li>

                </ul>
            </div>
            </nav>

        </div>

    </div>

</div>

<!-- caroussel -->

<div id="myCarousel" class="carousel slide carousel-fade" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
<div class="carousel-inner">
    <div class="carousel-item active">
    <img class="first-slide" src="/images/depart.jpg" alt="First slide">
    <div class="container">
        <div class="carousel-caption text-left">
        <h1>XXXX mobilisés</h1>
        <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
        <p class="text-right"><a class="btn btn-primary btn-sm" href="#" role="button">En savoir plus</a></p>
        </div>
    </div>
    </div>
    <div class="carousel-item">
    <img class="second-slide" src="/images/test-image-07.jpg" alt="Second slide">
    <div class="container">
        <div class="carousel-caption text-left">
        <h1>XX millions de morts</h1>
        <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
        <p class="text-right"><a class="btn btn-primary btn-sm" href="#" role="button">En savoir plus</a></p>
        </div>
    </div>
    </div>
    <div class="carousel-item">
    <img class="third-slide" src="/images/test-image-09.jpg" alt="Third slide">
    <div class="container">
        <div class="carousel-caption  text-left">
        <h1>XXXXX Prisonniers</h1>
        <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
        <p class="text-right"><a class="btn btn-primary btn-sm" href="#" role="button">En savoir plus</a></p>
        </div>
    </div>
    </div>
</div>

</div>