<div class="container">

    <header class="row">

        <hgroup class="col-12 text-center">

            <a href="/index.php">
            
                <img src="/images/grand-logo.svg" class="logo" alt="Logo du site Histoires de Poilus"/></a>

            </a>

        </hgroup>

        <div class="col-12">

            <nav class="navbar navbar-expand-lg navbar-light">
            
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav mx-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Les Poilus
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="/poilus.php" title="Qu'est-ce qu'un poilu ?">A propos des poilus</a>
                        <a class="dropdown-item" href="/index_noms.php" title="Liste des noms de soldats cités sur le site">Index des noms cités</a>
                        <a class="dropdown-item" href="/poilus/lacourt-onesime.php" title="Biographies de soldats originaires des Ardennes">Les poilus des Ardennes</a>
                        <a class="dropdown-item" href="/poilus/FROIDUROT-Alfred.php" title="Biographies de soldats originaires de la Côte-d'Or">Les poilus de la Côte-d'Or</a>
                        <a class="dropdown-item" href="/poilus/arnould-gaston.php" title="Biographies de soldats originaires de la Marne">Les poilus de la Marne</a>
                        <a class="dropdown-item" href="/poilus/amand-hoche.php" title="Biographies de soldats originaires du Nord">Les poilus du Nord</a>
                        <a class="dropdown-item" href="/poilus/amand-jules.php" title="Biographies de soldats originaires de Belgique">Les jasses de Belgique</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Les Hôpitaux
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    	<a class="dropdown-item" href="/hopitaux/hopitaux.php" title="Organisation du système de santé pendant la Première Guerre Mondiale">Le système de santé pendant la Grande Guerre</a>
                        <a class="dropdown-item" href="/hopitaux/hopitaux-59.php" title="Liste non exhaustive des hôpitaux du Nord pendant la Grande Guerre">Les hôpitaux du Nord</a>
                        <a class="dropdown-item" href="/hopitaux/hopitaux-62.php" title="Liste non exhaustive des hôpitaux du Pas-de-Calais pendant la Grande Guerre">Les hôpitaux du Pas-de-Calais</a>
						<a class="dropdown-item" href="/hopitaux/hopitaux-80.php" title="Liste non exhaustive des hôpitaux de la Somme pendant la Grande Guerre">Les hôpitaux de la Somme</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="/tombes.php" role="button" aria-haspopup="true" aria-expanded="false">
                    Les Tombes
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Les Camps
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    	<a class="dropdown-item" href="/camps.php" title="Les camps de prisonniers situés en Allemagne pendant la Première Guerre Mondiale">Les camps de prisonniers en Allemagne</a>
						<a class="dropdown-item" href="/camps-fr/camps.php" title="Les camps de prisonniers situés en France pendant la Première Guerre Mondiale">Les camps de prisonniers en France</a>
						<a class="dropdown-item" href="/camps-nl/camps-internements.php" title="Les camps d'internement situés au Pays-Bas pendant la Première Guerre Mondiale">Les camps d'internement aux Pays-Bas</a>
						<a class="dropdown-item" href="/camps-s/internement-suisse.php" title="Les camps d'internement situés au Suisse pendant la Première Guerre Mondiale">Les camps d'internement en Suisse</a>
					</div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Les Batailles
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
						<a class="dropdown-item" href="/batailles/batailles-est.php" title="Les batailles du front de l'est pendant la Grande Guerre">L'Europe de l'Est</a>
						<a class="dropdown-item" href="/batailles/batailles-ouest.php" title="Les batailles du front de l'ouest pendant la Grande Guerre">L'Europe de l'Ouest</a>
						<a class="dropdown-item" href="/batailles/batailles-italie.php" title="Les batailles du front italien pendant la Grande Guerre">Le Front Italien</a>
						<a class="dropdown-item" href="/batailles/batailles-afrique.php" title="Les batailles du front africain pendant la Grande Guerre">Le Front Africain</a>
						<a class="dropdown-item" href="/batailles/batailles-orient.php" title="Les batailles au Moyen-Orien pendant la Grande Guerre">Le Front du Moyen-Orient</a>
						<a class="dropdown-item" href="/batailles/batailles-balkans.php" title="Les batailles dans les Balkans pendant la Grande Guerre">Le Front des Balkans</a>
					</div>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Les Ressources
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="/guides/parcours-soldat.php" title="Comment retrouver le parcours d'un poilu">Comment retrouver un poilus ?</a>
                        <a class="dropdown-item" href="/ressources/historiques-regiments.php" title=" ">Les historiques de régiments</a>
                        <a class="dropdown-item" href="/bibliographie.php" title=" ">Les ressources bibliographiques</a>
                        <a class="dropdown-item" href="/webographie.php" title=" ">Les ressources en ligne</a>
                    </div>
                </li>

                </ul>
            </div>
            </nav>

        </div>

    </header>

</div>

<!-- caroussel -->

<div id="myCarousel" class="carousel slide carousel-fade" data-ride="carousel" style="margin-top:20px">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
<div class="carousel-inner">
    <div class="carousel-item active" style="background-image:url('/images/test-image-01.jpg'); background-size:cover;background-position: center;">
    <div class="container">
        <div class="carousel-caption text-left">
        <h1>Des millions de mobilisés</h1>
        <p>Dés juillet 1914, des millions d'hommes venus d'horizons diverses sont mobilisées par les bélligérants. 4 ans plus tard le bilan est lourd de 10 millions de morts ou disparus et 8 millions d'invalides, blessés lours et gueules cassées.</p>
        <p class="text-right"><a class="btn btn-primary btn-sm" href="/poilus.php" role="button">En savoir plus</a></p>
        </div>
    </div>
    </div>
    <div class="carousel-item" style="background-image:url('/images/test-image-02.jpg'); background-size:cover;background-position: center;">
    <div class="container">
        <div class="carousel-caption text-left">
        <h1>10 millions de morts</h1>
        <p>La Grande Guerre, c'est un bilan de 10 millions de morts ou disparus et 8 millions d'invalides, blessés lourds et gueules cassées.</p>
        <p class="text-right"><a class="btn btn-primary btn-sm" href="/tombes.php" role="button">En savoir plus</a></p>
        </div>
    </div>
    </div>
    <div class="carousel-item" style="background-image:url('/images/test-image-04.jpg'); background-size:cover;background-position: center;">
    <div class="container">
        <div class="carousel-caption  text-left">
        <h1>8 000 000 de Prisonniers</h1>
        <p>Environs 8 000 000 de civils et de militaires ont été fait prisonniers pendant le premier conflit mondial.</p>
        <p class="text-right"><a class="btn btn-primary btn-sm" href="/camps.php" role="button">En savoir plus</a></p>
        </div>
    </div>
    </div>
</div>

</div>