<a href="amand-hoche.php" class="list-group-item">AMAND Hoche</a>
<a href="amand-marceau.php" class="list-group-item">AMAND Marceau</a>
<a href="bottiau-raphael-joseph.php" class="list-group-item">BOTTIAU Raphaël Joseph</a>
<a href="boucher-gervais.php" class="list-group-item">BOUCHER Gervais</a>
<a href="boursier-edouard.php" class="list-group-item">BOURSIER Edouard</a>
<a href="BOURSIER-Jules.php" class="list-group-item">BOURSIER Jules Henri</a>
<a href="carin-alfred.php" class="list-group-item">CARIN Alfred</a>
<a href="CARIN-Edouard.php" class="list-group-item">CARIN Édouard (+)</a>
<a href="carin-jean-baptiste.php" class="list-group-item">CARIN Jean Baptiste</a>
<a href="carin-joseph.php" class="list-group-item">CARIN Joseph</a>
<a href="CARIN-Leon.php" class="list-group-item">CARIN Léon (+)</a>
<a href="CARIN-Theophile.php" class="list-group-item">CARIN Théophile</a>
<a href="CARLIER-Druon-Joseph.php" class="list-group-item">CARLIER Druon Joseph</a>
<a href="CARLIER-Louis-Abraham.php" class="list-group-item">CARLIER Louis Abraham</a>
<a href="delaux-oscar-julien.php" class="list-group-item">DELAUX Oscar Julien</a> 
<a href="DUBOIS-Emile-Edmond.php" class="list-group-item">DUBOIS Émile Edmond (+)</a>
<a href="dubois-jean-charles.php" class="list-group-item">DUBOIS Jean Charles (+)</a>
<a href="FIEVET-Auguste-Victor.php" class="list-group-item">FIEVET Auguste Victor</a>
<a href="FIEVET-Charles-Augustin.php" class="list-group-item">FIEVET Charles Augustin</a>
<a href="FONTAINE-Henri-Gustave.php" class="list-group-item">FONTAINE Henri Gustave</a>
<a href="GRAIN-Leon-Albert.php" class="list-group-item">GRAIN Léon Albert</a>
<a href="GRAIN-Louis.php" class="list-group-item">GRAIN Louis</a>
<a href="hanze-augustin.php" class="list-group-item">HANZE Augustin (+)</a>
<a href="JOLY-Noel-Jules.php" class="list-group-item">JOLY Noël Jules</a>
<a href="lamandin-georges.php" class="list-group-item">LAMANDIN Georges (+)</a>
<a href="lesage-jules-joseph.php" class="list-group-item">LESAGE Jules Joseph</a>
<a href="LETIENNE-Florimond.php" class="list-group-item">LETIENNE Florimond</a>
<a href="magny-jules.php" class="list-group-item">MAGNY Jules</a>
<a href="mascart-emile.php" class="list-group-item">MASCART Émile</a>
<a href="mascart-leon.php" class="list-group-item">MASCART Léon</a>
<a href="mascart-leon-2.php" class="list-group-item">MASCART Léon (+)</a>
<a href="mascart-louis.php" class="list-group-item">MASCART Louis (+)</a>
<a href="masquellier-jean-baptiste.php" class="list-group-item">MASQUELLIER Jean-Baptiste</a>
<a href="patou-druon-adrien.php" class="list-group-item">PATOU Druon Adrien (+)</a>
<a href="pelez-alfred.php" class="list-group-item">PELEZ Alfred</a>
<a href="rousseaux-eugene-fernand.php" class="list-group-item">ROUSSEAUX Eugène Fernand</a><!-- TODO -->
<a href="ROUSSEAUX-Louis.php" class="list-group-item">ROUSSEAUX Louis Henri (+)</a>
<a href="tiburce-louis.php" class="list-group-item">TIBURCE Louis</a>
<a href="vanesse-alfred.php" class="list-group-item">VANESSE Alfred</a>
<a href="VELU-Adrien.php" class="list-group-item">VELU Adrien (+)</a>