<div id="navbis">
    <a href="poilus/lacourt-onesime.php">Les poilus des Ardennes</a>&nbsp;&nbsp;|&nbsp;&nbsp;
    <a href="amand-hoche.php">Les poilus du Nord</a>&nbsp;&nbsp;|&nbsp;&nbsp;
    <a href="arnould-gaston.php">Les poilus de la Marne</a>&nbsp;&nbsp;|&nbsp;&nbsp;
    <a href="FROIDUROT-Alfred.php">Les poilus de la Côte-d'Or</a>&nbsp;&nbsp;|&nbsp;&nbsp;
    <a href="amand-jules.php">Les jasses de Belgique</a>
</div>