<a href="arnould-gaston.php" class="list-group-item menutest">ARNOULD Gaston</a>
<a href="arnould-henri-rene.php" class="list-group-item menutest">ARNOULD Henri René (+)</a>
<a href="astiers-jules-alphonse.php" class="list-group-item menutest">ASTIER(S) Jules Alphonse</a> 
<a href="BALTAZART-Ernest-Auguste.php" class="list-group-item menutest">BALTAZART Ernest Auguste</a>
<a href="caron-eugene-alexandre.php" class="list-group-item menutest">CARON Eugène Alexandre</a>
<a href="MAILLART-Alexandre.php" class="list-group-item menutest">MAILLART Alexandre Ernest</a>
<a href="MICHEL-Firmin.php" class="list-group-item menutest">MICHEL Firmin (+)</a>
<a href="paquet-leopold.php" class="list-group-item menutest">PAQUET Léopold</a>