<nav>	
    <a href="../contact.php">Contact</a>
    <a href="../webographie.php">Les Ressources</a>
    <a href="../lieux.php">Les Batailles</a>
    <a href="../camps.php">Les Camps</a>
    <a href="../tombes.php">Les Tombes</a>
    <a href="hopitaux.php" class="NavSelected">Les Hôpitaux</a>
    <a href="../poilus.php">Les Poilus</a>	
</nav>

<div id="navbis">
    <a href="hopitaux-59.php">hôpitaux du Nord</a>&nbsp;&nbsp;|&nbsp;&nbsp;
    <a href="hopitaux-62.php">hôpitaux du Pas-de-Calais</a>&nbsp;&nbsp;|&nbsp;&nbsp;
    <a href="hopitaux-80.php">hôpitaux de la Somme</a>&nbsp;&nbsp;|&nbsp;&nbsp;
</div>