<a href="arnould-gaston.php" class="list-group-item">ARNOULD Gaston</a>
<a href="arnould-henri-rene.php" class="list-group-item">ARNOULD Henri René (+)</a>
<a href="astiers-jules-alphonse.php" class="list-group-item">ASTIER(S) Jules Alphonse</a> 
<a href="BALTAZART-Ernest-Auguste.php" class="list-group-item">BALTAZART Ernest Auguste</a>
<a href="caron-eugene-alexandre.php" class="list-group-item">CARON Eugène Alexandre</a>
<a href="MAILLART-Alexandre.php" class="list-group-item">MAILLART Alexandre Ernest</a>
<a href="MICHEL-Firmin.php" class="list-group-item">MICHEL Firmin (+)</a>
<a href="paquet-leopold.php" class="list-group-item">PAQUET Léopold</a>