                <nav class="navbar navbar-expand-lg navbar-light">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler01" aria-controls="navbarToggler01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse mx-auto" id="navbarToggler01">
                    <ul class="navbar-nav mx-auto">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Les Poilus
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="/poilus.php">A propos des poilus</a>
                                <a class="dropdown-item" href="/poilus/lacourt-onesime.php">Les poilus des Ardennes</a>
                                <a class="dropdown-item" href="/poilus/amand-hoche.php">Les poilus des Nord</a>
                                <a class="dropdown-item" href="/poilus/arnould-gaston.php">Les poilus de la Marne</a>
                                <a class="dropdown-item" href="//FROIDUROT-Alfred.php">Les poilus de la Côte-d'Or</a>
                                <a class="dropdown-item" href="/poilus/amand-jules.php">Les jasses de Belgique</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Les Hôpitaux
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="/hopitaux/hopitaux.php">Le système de santé pendant la Grande Guerre</a>
                                <a class="dropdown-item" href="/hopitaux/hopitaux-59.php">Les hôpitaux du Nord</a>
                                <a class="dropdown-item" href="/hopitaux/hopitaux-62.php">Les hôpitaux du Pas-de-Calais</a>
                                <a class="dropdown-item" href="/hopitaux/hopitaux-80.php">Les hôpitaux de la Marne</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/tombes.php">Les Tombes</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Les Camps
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="/camps.php">Les camps de prisonniers en Allemagne</a>
                                <a class="dropdown-item" href="/camps-nl/camps-internements.php">Les camps d'internement aux Pays-Bas</a>
                                <a class="dropdown-item" href="/camps-s/internement-suisse.php">Les camps d'internement en Suisse</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Les Batailles
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="/batailles/batailles-est.php">L'Europe de l'Est</a>
                                <a class="dropdown-item" href="/batailles/batailles-ouest.php">L'Europe de l'Ouest</a>
                                <a class="dropdown-item" href="/batailles/batailles-italie.php">Le Front Italien</a>
                                <a class="dropdown-item" href="/batailles/batailles-afrique.php">Le Front Africain</a>
                                <a class="dropdown-item" href="/batailles/batailles-orient.php">Le Front du Moyen-Orient</a>
                                <a class="dropdown-item" href="/batailles/batailles-balkans.php">Le Front des Balkans</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Les Ressources
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="/guides/parcours-soldat.php">Comment retrouver un poilus ?</a>
                                <a class="dropdown-item" href="/bibliographie.php">Les ressources bibliographiques</a>
                                <a class="dropdown-item" href="/webographie.php">Les ressources en ligne</a>
                            </div>
                        </li>
                        </ul>
                    </div>
                </nav>