<nav>
	<a href="../contact.php">Contact</a>
    <a href="../webographie.php">Webographie</a>
    <a href="../lieux.php">Les Batailles</a>
    <a href="../camps.php" class="NavSelected">Les Camps</a>
    <a href="../releves.php">Les Relevés</a>
    <a href="../hopitaux/hopitaux.php">Les Hôpitaux</a>
    <a href="../poilus.php">Les Poilus</a>
</nav>

<div id="navbis">
	<a href="../camps.php">Les camps de prisonniers en Allemagne</a>&nbsp;&nbsp;|&nbsp;&nbsp;
	<a href="../camps-nl/camps-internements.php">Les camps d'internement aux Pays-Bas</a>&nbsp;&nbsp;|&nbsp;&nbsp;
	<a href="../camps-s/internement-suisse.php">Les camps d'internement en Suisse</a>
</div>