<i class="fas fa-bars" id="btnresp" onclick="affiche('menuresp')"></i>

<div id="menuresp">

<ul>
	<li><a href="../poilus.php">Les Poilus</a></li>
	<li><a href="../hopitaux/hopitaux.php">Les Hôpitaux</a></li>
	<li><a href="../releves.php">Les Relevés</a></li>
	<li><a href="../camps.php">Les Camps</a></li>
	<li><a href="../lieux.php">Les Batailles</a></li>
	<li><a href="../webographie.php">Webographie</a></li>
	<li><a href="../contact.php">Contact</a></li>
</ul>

</div>